# 잔디먹는 뱀!!

name: generate animation

on:
  # run automatically every 24 hours
  schedule: 
    # 24시간마다 한 번
    - cron: "0 */24 * * *"

  # allows to manually run the job at any time
  # 자동으로 action이 실행되도록 함
  workflow_dispatch: 

  # run on every push on the master branch
  push:
    branches:
    - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # generates a snake game from a github user(<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Clotilde030603
          outputs: |
            # dist/github-contribution-grid-snake.svg
            # dist/contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-snake-dark.svg?color_snake=
            
          

    
